services:
  media-cleaner-web:
    image: ghcr.io/arnavy15/media-cleaner:1.0.1
    container_name: media-cleaner
    restart: unless-stopped
    ports:
      - "5050:5050"
    volumes:
      - /your/server/config:/config
      - /your/server/download:/download
      - /your/server/media:/media
