version: "3.9"

services:
  media-cleaner-web:
    image: ghcr.io/arnavy15/media-cleaner:latest
    container_name: media-cleaner-web
    restart: unless-stopped
    ports:
      - "5050:5050"
    volumes:
      - /your/server/config:/config
      - /your/server/download:/download
      - /your/server/media:/media
